### ISSUE TITLE
vector_sincos

### ISSUE THREAD

**Issue by niello** [nfrechette/rtm#104]
Hi.
Could you please add a `vector_sincos` routine? It looks like a major part of `vector_sin` and `vector_cos` is the same, so unifying them must provide some speed-up.

It is especially useful e.g. for reconstructing quaternions from axis&angle four at a time, [like here](https://github.com/niello/deusexmachina/blob/9225829cb611918de5fa787d3d64a6849c519229/DEM/Low/src/Animation/Inertialization.cpp#L409).

**Comment by nfrechette** [comment]
Hello,
Thank you for the suggestion.

I will see if I have time this week to implement this. I am planning to release the next version of RTM in the next few days and I'll be adding a few missing things like this.

Do you use Structures of Array a lot with math like this? I am currently sitting on the fence about whether or not to add SOA variants directly within RTM. I've already implemented a few elsewhere. I think for clarity I would add them under a nested namespace `rtm::soa`. Thoughts?

**Comment by niello** [comment]
Sounds great about the new release. Hope that means that you plan to release new ACL too)

I do not use vector math widely at all at this point, but I am impressed with 3x speedup from vectorizing inertialization and I plan to optimize other critical parts of my code in the future. From my taste SoA would reduce readability at least for that linked code. Maybe you can explain your idea with some example and show where SoA would improve? Then I can tell you what I think of it.

And a small question probably not worth an additional issue. Is there a way to access vector/quat components by index without reducing performance? For now I have to unwrap loops to use xyzw and abcd explicitly instead of [0/1/2/3].

**Comment by nfrechette** [comment]
That's correct, once RTM is released later this week, I'll be working my way towards releasing ACL 2.0. I'm almost there, I just need to update RTM, run final validation, extract the stats/graphs, etc. Final touches basically. ACL 2.0 will now exclusively use RTM for its math (with a few exceptions).

Yes, by SOA I mean that instead of processing 1 item at a time (e.g. vec3, quat), you process 4 at a time. It does make the code a lot less friendly to read and debug and IMO should only be used in very hot code for those reasons. Ordinary code would become too hard to write and debug to be worth it and if the code isn't run very often, then any performance gains from doing this are likely to vanish.

Accessing vector components by an index that isn't known at compile time is slow. SSE2 doesn't have any instructions for doing this efficiently (and I don't think NEON does either). Under the hood, we either have to branch dynamically at runtime or we have to store the whole vector to memory (stack) and reload the component we need (this would stall on older processors but now isn't as bad with store forwarding but still not great). It's best to avoid doing this as much as possible. For code that is very hot, you should look into rewriting it differently (perhaps even looping multiple times and doing transformation passes from one layout to the next, doing swizzles to realign SIMD elements, etc) but if the code isn't called terribly often then performance should be acceptable regardless.

**Comment by niello** [comment]
I use SoA only to vectorize 4 scalar operations. If you look at the code you will see that all operations on vectors and quaternions are either looped from 0 to 3 or unwrapped into 4 similar code blocks. But for scalars it works really cool. To be honest, I don't think my optimized code would cause performance problems if I left it scalar (one bone at a time). It was more of an excercise for me. If you have an example of a good SoA usage for multiple vectors or quats, it is interesting for me to see. And if there are some things already implemented it is worth adding to the library with an explaination on how to get the most from it. Separate `rtm::soa` namespace sounds good, there are already many things in the root.

I looked at vector_get_N routines. What if you add something like that:
```
float vector_get_component(int index)
{
#if defined(RTM_SSE4_INTRINSICS)
	return _mm_extract_ps(input, index);
#elif defined(RTM_SSE2_INTRINSICS)
	return _mm_cvtss_f32(_mm_shuffle_ps(input, input, _MM_SHUFFLE(index, index, index, index)));
#elif defined(RTM_NEON_INTRINSICS)
	return vgetq_lane_f32(input, index);
#else
	return input[index];
#endif
}
```

And vector_set_component counterpart with some permutation playing for SSE2. This will not use branching at all. It will be perhaps not so optimized because an index is not known at compile time. Or you don't want to encourage users to write code with dynamic index? It is convenient to loop from 0 to 3 to use scalars in further calculations, and if I was a compiler I would unwrap the loop by myself if I see it worth it.

BTW, looks strange that you don't use `_mm_extract_ps` in get. Is it an intent?

**Comment by nfrechette** [comment]
You can take a look at the new ACL decompression code, it uses SOA a bit where it makes sense. You can also check out this branch: https://github.com/nfrechette/acl/tree/optim/use-soa-mutable-tracks

_mm_extract_ps maps to [extractps](https://www.felixcloutier.com/x86/extractps) which stores the component into an integer register or into memory. You could use it to round-trip from the stack with a store/load if it accepted a dynamic component value but it does not: just like _mm_shuffle_ps, they both require an immediate value known at compile time.

The tradeoff thus becomes complicated. The current code will branch at runtime based on the component requested. The only viable alternative I can think of with SSE2/AVX would be to store on the stack and load the component we need, a 3-7 cycle cost, maybe more on older hardware. On the other hand if the branch is correctly predicted, the cost might be 1-2 cycles and even if it isn't, performance might average out to be about the same. Even if another alternative existed where we would need to load some mask or shift offset, that would imply a 8/16 byte load which cannot be predicted and requires 4-750+ cycles depending on whether we cache miss or not which will depend how often this function is called. If it isn't called often, the cost could end up being much more expensive than branching. Some code might end up faster when branching while some other code might be faster with a stack round trip. This depends on the code, data, and processor used. I basically made the executive decision to branch but if you can show me hard numbers that an alternate implementation performs better overall, I'd be happy to consider it.

Similarly, vgetq_lane_f32 expects an immediate value known at compile time. I'm not sure if NEON would allow a more efficient implementation than SSE2 (I'm not quite as familiar with NEON yet) but even if it does, I'd advise against relying on this in performance critical code that is meant to be portable.

**Comment by niello** [comment]
Oh, I got what you mean with SoA for vec/quat. Worth adding to the public interface from my PoV. And it is convenient if you leave function names the same as for single-object ops, but with a nested namespace, just as you suggested (`rtm::quat_mul` + `rtm::soa::quat_mul`).

Thank you very much for your answer about indexing. I should have spent more time investigating that before asking. Not to speak I thought that `imm` in SSE4 is an integer vector register, just like `xmm` or `ymm`. Pretty ridiculous)
