### ISSUE TITLE
Is it left- or right-handed?

### ISSUE THREAD

**Issue by legends2k** [nfrechette/rtm#109]
[`docs/api_conventions.md`](https://github.com/nfrechette/rtm/blob/develop/docs/api_conventions.md) says

> When relevant, a left-handed coordinate system is used:
>
>    X axis = forward
>    Y axis = right
>    Z axis = up

This seems incorrect.  The axes description given actually describes a [Right-hand system](https://en.wikipedia.org/wiki/Right-hand_rule).  Fix the axes description to agree with left-handed systems or change the sentence to say it's right-handed.

**Comment by nfrechette** [comment]
I'm not sure I follow, per your link:

> For left-handed coordinates the left thumb points along the Z axis in the positive direction and the curled fingers of the left hand represent a motion from the first or X axis to the second or Y axis. When viewed from the top or Z axis the system is clockwise. 

It follows that Z is up (thumb), X is forward as it rotates towards the Y axis (on the right) through the clockwise rotation of your fingers.

**Comment by legends2k** [comment]
Aah... you're right.  I thinking right _but imagining left_ 🤦🏾.  Sorry to have wasted your time.  Thanks for the reply :)

**Comment by nfrechette** [comment]
Glad we could sort it out :)

I agree, I'd love to add functionality like that at some point. I'm not sure I'll have the bandwidth any time soon but contributions are welcome. I think my main focus this year will be generating browsable documentation and adding WASM SIMD support.
