### ISSUE TITLE
Can't generate build files on Linux

### ISSUE THREAD

**Issue by ifschleife** [nfrechette/rtm#11]
Hi there.
This looks very interesting so I wanted to try it out but can't get cmake to generate the build files.
When I run `python make.py` I get:
```
Using config: Release
Using cpu: x64
Generating build files ...
Using default generator
Not searching for unused variables given on the command line.
-- The CXX compiler identification is GNU 8.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected platform: Linux
CMake Error at tests/main_generic/CMakeLists.txt:26 (include):
  include could not find load file:

    ParseAndAddCatchTests


CMake Error at tests/main_generic/CMakeLists.txt:27 (ParseAndAddCatchTests):
  Unknown CMake command "ParseAndAddCatchTests".
```

This is with cmake 3.13.3 on ArchLinux. I tried installing catch2 but that didn't help.

**Comment by nfrechette** [comment]
Make sure to pull submodules as well since catch2 is included that way
under external.
Note that this just generates build files for tools and unit tests as the
library is 100% headers.

**Comment by ifschleife** [comment]
Dang, I didn't realize there is no library to build. That's great, thanks. I should have read more carefully.

But maybe you could mention the submodule in the Getting Started guide? That step isn't in there, I think.
