### ISSUE TITLE
Add qvv_from_matrix

### ISSUE THREAD

**Issue by niello** [nfrechette/rtm#187]
Actually useful sometimes at least for matrix3x4f.

In the meantime I use this code:

```
RTM_DISABLE_SECURITY_COOKIE_CHECK RTM_FORCE_INLINE rtm::vector4f RTM_SIMD_CALL matrix_extract_scale(rtm::matrix3x4f_arg0 m) noexcept
{
	const float ScaleX = rtm::vector_length3(m.x_axis);
	const float ScaleY = rtm::vector_length3(m.y_axis);
	const float ScaleZ = rtm::vector_length3(m.z_axis);
	return rtm::vector_set(ScaleX, ScaleY, ScaleZ);
}
//---------------------------------------------------------------------

RTM_DISABLE_SECURITY_COOKIE_CHECK RTM_FORCE_INLINE rtm::qvvf RTM_SIMD_CALL qvv_from_matrix(rtm::matrix3x4f_arg0 m) noexcept
{
	const rtm::vector4f Scale = matrix_extract_scale(m);

	rtm::matrix3x3f RotationMatrix = rtm::matrix_cast(m);
	constexpr float THRESHOLD = 1.0E-8F;
	if (rtm::vector_get_x(Scale) >= THRESHOLD)
		RotationMatrix.x_axis = rtm::vector_div(m.x_axis, rtm::vector_dup_x(Scale));
	if (rtm::vector_get_y(Scale) >= THRESHOLD)
		RotationMatrix.y_axis = rtm::vector_div(m.y_axis, rtm::vector_dup_y(Scale));
	if (rtm::vector_get_z(Scale) >= THRESHOLD)
		RotationMatrix.z_axis = rtm::vector_div(m.z_axis, rtm::vector_dup_z(Scale));

	return rtm::qvv_set(rtm::quat_from_matrix(RotationMatrix), m.w_axis, Scale);
}
//---------------------------------------------------------------------
```

Note that `matrix_extract_scale` is outside intentionally because sometimes it is useful alone.
Perhaps you can figure out some way to improve component-wise comparison to threshold and normalizing axes.

**Comment by nfrechette** [comment]
Thank you for the suggestion!
You are quite right, it is indeed very handy. I'll add it in the next minor release.

**Comment by nfrechette** [comment]
I started looking at this and there is some nuance that complicates things.

You've only partially handled zero scale. If any axis is zero, we cannot reconstruct the rotation and we give up, returning identity (currently).

This also won't work if any axis has negative scale. If one or 3 axes have negative scale, winding is reversed (negative determinant). This will prevent the current code from finding a valid rotation as it assumes a valid rotation matrix. However,  if two axes have negative scale, the winding is preserved and we cannot detect their presence using the determinant (a rotation will be found, but it may not be the original one).

I'll have to give it some thought to see if we can be smart and reconstruct things properly.
