### ISSUE TITLE
Add vector_sqrt_reciprocal

### ISSUE THREAD

**Issue by niello** [nfrechette/rtm#193]
There is `scalar_sqrt_reciprocal` but no vector counterpart. There is a practical use for it though, e.g. normalizing 4 vectors at a time, which is useful for [building a view frustum for culling](https://github.com/niello/deusexmachina/blob/55095efe1fd4c264818b9efcb5fa5f8b7983dda8/DEM/Low/src/Math/CameraMath.h#L96).

Can you please add it?

**Comment by nfrechette** [comment]
That should be easy enough, I'll it to the next release backlog.
Thank you for the suggestion!
