### ISSUE TITLE
RTM_DEPRECATED is undefined when using RTM_NO_DEPRECATION

### ISSUE THREAD

**Issue by ea-rmccord** [nfrechette/rtm#211]
If RTM_NO_DEPRECATION is defined, then RTM_DEPRECATED is not, leading to compile errors.

**Comment by nfrechette** [comment]
Thank you for reporting this and bringing it to my attention.
I'll push out a fix for this once CI completes in the linked PR. If nothing else surfaces, I'll push out a patch release with the fix next weekend.

Cheers!

**Comment by nfrechette** [comment]
Fixed in `develop` and the new v2.3.1 release.
