### ISSUE TITLE
Some of the vector methods look prone to overflows and precision problems

### ISSUE THREAD

**Issue by bdezonia** [nfrechette/rtm#39]
The vector methods (like dot and squared_length etc.) use methods that do not behave well with large numbers or numbers with large differences in magnitude. Ideally they should do something like dividing the values first by the absolute max of the involved terms, calcing the dot of the scaled terms, and then scaling back to the original space. This handles data that could overflow better.

**Comment by nfrechette** [comment]
RTM is aimed for realtime applications such as video games and realtime simulations. This means that performance often takes precedence over safety for common operations where safety isn't needed. Usually it falls back on the caller to determine what is expected to be safe and what isn't. For example, handling 0 determinant in matrix inversion. When safety is required, functions offer a variant that does the sort of things you describe. e.g. `vector_dot(..)` and `vector_dot_safe(..)`.

The library is mostly optimized for float32 arithmetic at the moment and float64 can be used for more precision but ultimately if you attempt to use it in a scientific computing type environment that might not be enough and extra checks for overflow might be required.

For the time being, there are no safe variants but some are planned to come. Contributions are welcome.
